#! /bin/sh

# Setup the keyboard (under X only)
setxkbmap -layout dvorak,us -option ctrl:nocaps,grp:sclk_toggle

# Load the Xresources
if [ -d $HOME/.dotfiles/Xresources ]; then
    cat ~/.dotfiles/Xresources/* | xrdb
fi

# Set the background
if [ -d $HOME/images/wallpapers ] && [ `command -v xloadimage` ]; then
    random_bg=`find $HOME/images/wallpapers -type f | sort -R | head -n1`
    xloadimage -onroot -center -border black $random_bg
else
    xsetroot -solid steelblue
fi

# Starts a window manager
xmonad
