" Add locations needed by some plugins to $PATH
let $PATH = $PATH . ':' . expand("~/.cabal/bin")

set nocompatible        " Use vim default settings
filetype off            " Required by Vundle

" Load Vundle
set rtp+=~/.vim/bundle/vundle
call vundle#begin()

" Let Vundle manage itself ; required
Plugin 'gmarik/vundle'

Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/syntastic'
Plugin 'altercation/vim-colors-solarized'
Plugin 'pangloss/vim-javascript'

call vundle#end()
filetype plugin indent on

" General
set history=300         " Number of line of history vim should remember
set autoread            " Automatically reread a file if it has changed

" Press space to clear search highlighting and any message already displayed
nnoremap <silent> <Space> :silent noh<Bar>echo<CR>


" Interface
set title               " Show title in the console title bar
set ruler               " Show the current position inside the file

set mouse=a             " The mouse is usable in all modes
set scrolloff=10        " Keep 10 lines when scrolling

set expandtab           " Expand all tab characters to spaces
set tabstop=4           " A tab character is 4 spaces
set shiftwidth=4        " Shift is 4 spaces

set showmatch           " Show matching brackets/parentheses

set incsearch           " Incremental search
set smartcase           " Search becomes case sensitive only if captials are used

set noerrorbells        " No sound on errors
set novisualbell        " No flash on errors
set t_vb=

" Spellchecking
set spelllang=en
set dictionary=/usr/share/dict/words


" neco-ghc
" Show detailed information (type) about symbols
" let g:necoghc_enable_detailed_browse = 1


" neocomplcache
" let g:neocomplcache_enable_at_startup = 0

" <Tab> to select a completion
" inoremap <expr><Tab> pumvisible() ? "\<C-n>" : "\<Tab>"


" Supertab
" let g:SuperTabDefaultCompletionType = "context"
" let g:SuperTabClosePreviewOnPopupClose = 1


" Tags
set tags=./tags;


" Colors and fonts
syntax enable               " Enable syntax highlighting
set background=dark
colorscheme solarized


" File backups
set nobackup
set nowritebackup
set noswapfile


" Keymaps
map <F8> :TagbarToggle<CR>
map <F9> :make<CR>


if has("autocmd")
    autocmd FileType c,cpp,sh,pl set autoindent
    autocmd FileType c,cpp,sh,pl set smartindent
    autocmd FileType c,cpp,sh,pl set cindent

    autocmd BufRead,BufNewFile *.md set filetype=markdown

    autocmd FileType python set omnifunc=pythoncomplete#Complete
    autocmd FileType python set completeopt=menuone,longest,preview

    " For all text files set 'textwidth' to 78 characters
    autocmd FileType text setlocal textwidth=78

    " When editing a file, always jump to the last known cursor position.
    " Don't do it when the position is invalid or when inside an event handler
    " (happens when dropping a file on gvim).
    " Also don't do it when the mark is in the first line, that is the default
    " position when opening a file.
    autocmd BufReadPost *
        \ if line("'\"") > 1 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif

endif
