" Load Pathogen
" To disable a plugin add it's bundle name to the following list
let g:pathogen_disabled = ['supertab']
source ~/.vim/bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

" General
set nocompatible        " Use vim default settings
set history=300         " Number of line of history vim should remember
set autoread            " Automatically reread a file if it has changed

filetype on             " Automatic filetype detection
filetype plugin on      " Enable filetype specific plugins
filetype indent on      " Enable filetype specific indentation

" Press space to clear search highlighting and any message already displayed
nnoremap <silent> <Space> :silent noh<Bar>echo<CR>


" Interface
set title               " Show title in the console title bar
set ruler               " Show the current position inside the file

set mouse=a             " The mouse is usable in all modes
set scrolloff=10        " Keep 10 lines when scrolling

set expandtab           " Expand all tab characters to spaces
set tabstop=4           " A tab character is 4 spaces
set shiftwidth=4        " Shift is 4 spaces

set showmatch           " Show matching brackets/parentheses

set incsearch           " Incremental search
set smartcase           " Search becomes case sensitive only if captials are used

set noerrorbells        " No sound on errors
set novisualbell        " No flash on errors
set t_vb=

" Spellchecking
set spelllang=en
set dictionary=/usr/share/dict/words


" Supertab
let g:SuperTabDefaultCompletionType = "context"


" Tags
set tags=./tags;


" Colors and fonts
syntax enable               " Enable syntax highlighting
set background=dark
colorscheme solarized


" File backups
set nobackup
set nowritebackup
set noswapfile


" Keymaps
map <F8> :TagbarToggle<CR>
map <F9> :make<CR>


if has("autocmd")
    autocmd FileType c,cpp,sh,pl set autoindent
    autocmd FileType c,cpp,sh,pl set smartindent
    autocmd FileType c,cpp,sh,pl set cindent
endif
